packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  esbuild: true
  electron-winstaller: true
  lmdb: true
  msgpackr-extract: true
  prisma: true
